<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PropertyInventory.Services</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PropertyInventory.Interfaces\PropertyInventory.Interfaces.csproj" />
    <ProjectReference Include="..\PropertyInventory.Models\PropertyInventory.Models.csproj" />
  </ItemGroup>
</Project>
